# Generated by Django 3.2.2 on 2021-05-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_auto_20210530_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_countries',
            new_name='published_countries',
        ),
    ]
